services:
    endroid_demo.importer.product_importer:
        class: Endroid\Import\Importer\Importer
        factory: ['Endroid\Import\Importer\ImporterFactory', createImporter]
        arguments:
            - '@endroid_demo.loader.product_collection_loader'
            - '@endroid_demo.loader.website_product_loader'
            - '@endroid_demo.loader.mobile_product_loader'
    endroid_demo.loader.product_collection_loader:
        class: Endroid\Import\DemoBundle\Loader\ProductCollectionLoader
    endroid_demo.loader.website_product_loader:
        class: Endroid\Import\DemoBundle\Loader\WebsiteProductLoader
    endroid_demo.loader.mobile_product_loader:
        class: Endroid\Import\DemoBundle\Loader\MobileProductLoader