services:

    # Import employees and related data
    endroid_import_demo.importer.employees:
        class: Endroid\Import\Importer\Importer
        arguments:
            - [
                  '@endroid_import_demo.loader.employee_loader',
                  '@endroid_import_demo.loader.office_loader',
                  '@endroid_import_demo.loader.location_loader'
              ]
        tags:
            - { name: endroid.import.importer, alias: employees }
    endroid_import_demo.loader.employee_loader:
        class: Endroid\Import\Bundle\ImportDemoBundle\Loader\EmployeeLoader
    endroid_import_demo.loader.office_loader:
        class: Endroid\Import\Bundle\ImportDemoBundle\Loader\OfficeLoader
    endroid_import_demo.loader.location_loader:
        class: Endroid\Import\Bundle\ImportDemoBundle\Loader\LocationLoader