services:
    endroid_import_demo.importer.employees:
        class: Endroid\Import\Importer\Importer
        arguments:
            - [
                  '@endroid_import_demo.loader.employee',
                  '@endroid_import_demo.loader.office',
                  '@endroid_import_demo.loader.location'
              ]
        tags:
            - { name: endroid.import.importer, alias: employees }
    endroid_import_demo.loader.employee:
        class: Endroid\Import\Bundle\ImportDemoBundle\Loader\EmployeeLoader
    endroid_import_demo.loader.office:
        class: Endroid\Import\Bundle\ImportDemoBundle\Loader\OfficeLoader
    endroid_import_demo.loader.location:
        class: Endroid\Import\Bundle\ImportDemoBundle\Loader\LocationLoader