services:
    endroid_guide.guide:
        class: Endroid\Guide\Guide
    endroid_guide.loader.epguides:
        class: Endroid\Guide\Loader\EpguidesLoader
        arguments: [ '@cache.app' ]
        tags:
            - { name: endroid_guide.loader }
    endroid_guide.loader.luckytv:
        class: Endroid\Guide\Loader\LuckyTvLoader
        tags:
            - { name: endroid_guide.loader }
    endroid_guide.loader.npo:
        class: Endroid\Guide\Loader\NpoLoader
        tags:
            - { name: endroid_guide.loader }
    endroid_guide.loader.rtl:
        class: Endroid\Guide\Loader\RtlLoader
        tags:
            - { name: endroid_guide.loader }